version: "3.8"

services:
  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    entrypoint: ["sh", "/app/entrypoint.sh"]
    volumes:
      - "./services/backend:/app"
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/app_dev
      - FLASK_ENV=development
      - APP_SETTINGS=app.config.DevelopmentConfig
      - SECRET_KEY=secret
    depends_on:
      - db

  db:
    build:
      context: ./services/db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    ports:
      - "80:3000"   # 🔥 Aquí corregimos para que
